-- Script para crear las tablas en Supabase
-- Ejecuta este script en el SQL Editor de Supabase

-- Tabla de usuarios
CREATE TABLE usuarios (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nombre TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  rol TEXT NOT NULL,
  direccion TEXT DEFAULT '',
  telefono TEXT DEFAULT '',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de ofertas
CREATE TABLE ofertas (
  id_oferta BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  restaurante_id BIGINT NOT NULL REFERENCES usuarios(id),
  descripcion TEXT NOT NULL,
  info_detallada TEXT,
  precio REAL NOT NULL,
  cantidad_disponible INTEGER NOT NULL,
  categoria TEXT NOT NULL,
  alergenos TEXT DEFAULT '',
  estado TEXT DEFAULT 'Activa',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de pedidos
CREATE TABLE pedidos (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  usuario_id BIGINT NOT NULL REFERENCES usuarios(id),
  oferta_id BIGINT NOT NULL REFERENCES ofertas(id_oferta),
  codigo_recoleccion TEXT NOT NULL,
  estado TEXT DEFAULT 'Pendiente',
  fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de donaciones
CREATE TABLE donaciones (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  albergue_id BIGINT NOT NULL REFERENCES usuarios(id),
  restaurante_id BIGINT NOT NULL REFERENCES usuarios(id),
  descripcion TEXT NOT NULL,
  cantidad INTEGER NOT NULL,
  estado TEXT DEFAULT 'Pendiente',
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Índices para mejorar rendimiento
CREATE INDEX idx_ofertas_restaurante ON ofertas(restaurante_id);
CREATE INDEX idx_ofertas_estado ON ofertas(estado);
CREATE INDEX idx_pedidos_usuario ON pedidos(usuario_id);
CREATE INDEX idx_pedidos_oferta ON pedidos(oferta_id);
CREATE INDEX idx_pedidos_estado ON pedidos(estado);
CREATE INDEX idx_donaciones_albergue ON donaciones(albergue_id);
CREATE INDEX idx_donaciones_restaurante ON donaciones(restaurante_id);
